// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWNS9bGyVv91J-zydlt3cE0-fVjy2_FNE',
    appId: '1:576169110678:web:55a74df9bfcfbfd47826b7',
    messagingSenderId: '576169110678',
    projectId: 'buzzer-app-2ae17',
    authDomain: 'buzzer-app-2ae17.firebaseapp.com',
    storageBucket: 'buzzer-app-2ae17.firebasestorage.app',
    measurementId: 'G-W981X9NY0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_OgF86FALDV14PlYqRc_Z7pvsn_2Sfj4',
    appId: '1:576169110678:android:79cee989c17f75cd7826b7',
    messagingSenderId: '576169110678',
    projectId: 'buzzer-app-2ae17',
    storageBucket: 'buzzer-app-2ae17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo4deKhJEFip_4WaSEJzXgDOBQ1yrZ9jc',
    appId: '1:576169110678:ios:1cb6f9389de844f67826b7',
    messagingSenderId: '576169110678',
    projectId: 'buzzer-app-2ae17',
    storageBucket: 'buzzer-app-2ae17.firebasestorage.app',
    iosBundleId: 'com.example.buzzerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo4deKhJEFip_4WaSEJzXgDOBQ1yrZ9jc',
    appId: '1:576169110678:ios:1cb6f9389de844f67826b7',
    messagingSenderId: '576169110678',
    projectId: 'buzzer-app-2ae17',
    storageBucket: 'buzzer-app-2ae17.firebasestorage.app',
    iosBundleId: 'com.example.buzzerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWNS9bGyVv91J-zydlt3cE0-fVjy2_FNE',
    appId: '1:576169110678:web:5925b1bc02ec79ea7826b7',
    messagingSenderId: '576169110678',
    projectId: 'buzzer-app-2ae17',
    authDomain: 'buzzer-app-2ae17.firebaseapp.com',
    storageBucket: 'buzzer-app-2ae17.firebasestorage.app',
    measurementId: 'G-19G145PT7E',
  );
}
